# Exercise - Getting and Knowing your Data-Occupation Dataset

This time we are going to pull data directly from the internet.


### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [3]:
df=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [4]:
users=df

### Step 4. See the first 25 entries

In [5]:
users.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Step 5. See the last 10 entries

In [6]:
users.tail(10)

     user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [10]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

In [11]:
users.shape[1]

5

### Step 8. Print the name of all the columns.

In [14]:
for x in users.columns:
  print(x)

user_id
age
gender
occupation
zip_code

### Step 9. How is the dataset indexed?

In [17]:
users.loc

### Step 10. What is the data type of each column?

In [18]:
users.dtypes

user_id        int64
age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

In [19]:
users.occupation

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [30]:
df['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

### Step 13. What is the most frequent occupation?

In [22]:
users.occupation.max()

'writer'

### Step 14. Summarize the DataFrame.

In [31]:
users.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### Step 15. Summarize all the columns

In [32]:
users.describe(include="all")

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [33]:
users.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

In [34]:
users.age.mean()

34.05196182396607

### Step 18. What is the age with least occurrence?

In [35]:
df['age'].min()

7